---
- name: install zsh
  include_tasks: zsh.yml

- name: install zsh plugin(s)
  include_tasks: zsh-plugins.yml
  when: zsh_plugins_git or zsh_plugins_package_manager

- name: install oh-my-zsh
  include_tasks: oh-my-zsh-install.yml
  when: omz_install

- name: configure oh-my-zsh
  include_tasks: oh-my-zsh-configure.yml
  when: omz_configure
