---
- name: Converge
  hosts: all
  vars:
    zsh_user_name: molecule
    zsh_user_group: molecule
    zsh_plugins_git:
      - name: zsh-syntax-highlighting
        zsh_file: zsh-syntax-highlighting.zsh
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      - name: zsh-autosuggestions
        zsh_file: zsh-autosuggestions.zsh
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
      - name: powerlevel10k
        zsh_file: powerlevel10k.zsh-theme
        repo: https://github.com/romkatv/powerlevel10k.git
    zsh_plugins_package_manager:
      - powerline
    omz_zsh_theme: "robbyrussel"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: ensure preReq pckgs are installed
      apt:
        name:
          - git
          - curl
          - wget
          - vim
        state: present

  tasks:
    - name: "Include ansible-role-zsh"
      include_role:
        name: "ansible-role-zsh"
