---
- name: Converge
  hosts: all
  vars:
    users:
      - name: vagrant
        group: vagrant
      - name: ipsum
        group: ipsum

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    - name: ensure preReq pckgs are installed
      apt:
        name:
          - git
          - curl
          - wget
          - vim
        state: present

  tasks:
    - name: "Include ansible-role-zsh"
      include_role:
        name: "ansible-role-zsh"
      vars:
        zsh_user: "{{ item }}"
        with_items: "{{ users }}"
